//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperHeroes.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperHeroes.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Birth date must be in UTC!.
        /// </summary>
        public static string BIRTH_DATE_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("BIRTH_DATE_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Birth date is required!.
        /// </summary>
        public static string BIRTH_DATE_REQUIRED_ERROR {
            get {
                return ResourceManager.GetString("BIRTH_DATE_REQUIRED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Description is required!.
        /// </summary>
        public static string DESCRIPTION_REQUIRED_ERROR {
            get {
                return ResourceManager.GetString("DESCRIPTION_REQUIRED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The birth date must be before the current date!.
        /// </summary>
        public static string FUTURE_BIRTH_DATE_ERROR {
            get {
                return ResourceManager.GetString("FUTURE_BIRTH_DATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Height is required!.
        /// </summary>
        public static string HEIGHT_REQUIRED_ERROR {
            get {
                return ResourceManager.GetString("HEIGHT_REQUIRED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hero name is required!.
        /// </summary>
        public static string HERO_NAME_REQUIRED_ERROR {
            get {
                return ResourceManager.GetString("HERO_NAME_REQUIRED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hero name is already in use!.
        /// </summary>
        public static string HERO_NAME_TAKEN_ERROR {
            get {
                return ResourceManager.GetString("HERO_NAME_TAKEN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name is required!.
        /// </summary>
        public static string NAME_REQUIRED_ERROR {
            get {
                return ResourceManager.GetString("NAME_REQUIRED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Super hero not found!.
        /// </summary>
        public static string SUPER_HERO_NOT_FOUND_ERROR {
            get {
                return ResourceManager.GetString("SUPER_HERO_NOT_FOUND_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A super hero cannot have duplicate super powers!.
        /// </summary>
        public static string SUPER_POWER_DUPLICATED_ERROR {
            get {
                return ResourceManager.GetString("SUPER_POWER_DUPLICATED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A super hero must have at least one super power!.
        /// </summary>
        public static string SUPER_POWER_REQUIRED_ERROR {
            get {
                return ResourceManager.GetString("SUPER_POWER_REQUIRED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Super powers not found!.
        /// </summary>
        public static string SUPER_POWERS_NOT_FOUND_ERROR {
            get {
                return ResourceManager.GetString("SUPER_POWERS_NOT_FOUND_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Weight is required!.
        /// </summary>
        public static string WEIGHT_REQUIRED_ERROR {
            get {
                return ResourceManager.GetString("WEIGHT_REQUIRED_ERROR", resourceCulture);
            }
        }
    }
}
