services:
  postgres:
    image: postgres:13.21-alpine3.21
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=superheroes_db
